### ISSUE TITLE
How to import this project.

### ISSUE THREAD

**Issue by 8622153** [ryuz/jelly#1]
ryuzさん，こんにちは．
私は現在ZYBO-Z7-20とRPi-cam(imx219)の接続テストをしていて，
ryuzさんのzybo_z7_imx219プロジェクトをインポート・テストしてみたいと思っています．
ですがインポート方法がわかりません．
方法でも参考となる資料でもなんでも構いません．ご教授頂きたく思っております．
宜しくお願い致します．
デバイス：ZYBO-Z7-20，RPI camera V2(imx219)
開発環境のバージョン： 2018.3 or 2017.4

Hi ryuz,
I want to import your project (jelly/projects/zybo_z7_imx219/) to my project.
But I couldn't understand how to import.
Please let us know. Thanks.

**Comment by ryuz** [comment]
こんばんは、ご連絡有難うございます。
このプロジェクトはしばらく使っていなかったので、これから再確認してみようと思います。
具体的にどの段階でで困っておられますでしょうか？

取り急ぎですが、関連の情報は少しブログなどにも記載しています。

http://ryuz.txt-nifty.com/blog/2018/04/zybo-z7-raspber.html
http://ryuz.txt-nifty.com/blog/2018/05/zybo-z7-raspber.html

あと、手元に無いのですが、先日書店で見かけたInterface誌(7月号)が確かラズパイカメラの記事があったので参考になる情報があるかもしれません。

**Comment by ryuz** [comment]
お世話になります。Ryuzです。いろいろミスがあったようです。
まず、RTLのディレクトリを整理した再に、プロジェクトの修正が出来ていませんでした。
projects/zybo_z7_imx219/syn/vivado2017.4
のみですが、先ほど修正したものを push いたしました。

gitにはblockデザインを入れていないので tcl から作る必要があります。

zybo_z7_imx219 を vivado で開いた後に、メニューの Tools -> Run Tcl Script で design_1.tcl を実行してください。

また、動作には ARM のソフトも必要です。
当方は @ikwzm氏の debian イメージを利用させてもらっています。

https://qiita.com/ikwzm/items/7e90f0ca2165dbb9a577


この上で OpenCV を独自に make して使っています。

また、uioを使うために device-tree も必要です。
jelly.dtsを入れておきましたので参考にしてください。

カメラを設定して画像を表示するソフトは
projects/zybo_z7_imx219/app
にあります。

その他不明点、またお問い合わせください。

**Comment by 8622153** [comment]
Ryuzさん
実装方法及参考資料の細かい説明，ありがとうございます．
vivado上での展開，Generate Bitstreamは正常に完了できました．
SWの方は今後検討していきます．
早々のご対応ありがとうございました．

**Comment by 8622153** [comment]
ryuzさん、お世話になっております．
再度質問させてください．
以前教えて頂いた上記の通りPL Configuration作成、PSでの実行を試してみたのですが、うまく動作していません．エラーは出力されてませんが、入力データに変化がなく、capture_still_image()後は全データが255になっています．LD3（frame_toggle）が点滅しませんので、データ受信のPL・制御に問題があるのかなと想定しています（i2cは読めています）．

解決策等ありましたらご教授いただきたく思っております．

以下、私が行った手順です．
（PC環境の問題かもしれませんのでryuzさんの元で再度実装確認頂ければ幸いです）
環境：ZYBO-Z7-20、vivado 2019.1、debian 9、u-boot 4.14.34
（PL）
・zybo_z7_imx219.xprを開く．
・design_1.tclを実行．（既にdesign_1.bdがあるとエラーするので事前に削除）
・Generate Bitstream実行．top.bitをSDにコピー．
（PS）
・@ikwzm氏のFPGA-SoC-Linuxをお借りして実装．
・device-treeを編集、追加ライブラリ（OpenCV等）を実装．
・プログラムをmake、root実行．

宜しくお願い致します．

**Comment by 8622153** [comment]
ryuzさん、お世話になっております．
再度質問させてください．
以前教えて頂いた上記の通りPL Configuration作成、PSでの実行を試してみたのですが、うまく動作していません．エラーは出力されてませんが、入力データに変化がなく、capture_still_image()後は全データが255になっています．LD3（frame_toggle）が点滅しませんので、データ受信のPL・制御に問題があるのかなと想定しています（i2cは読めています）．

解決策等ありましたらご教授いただきたく思っております．

以下、私が行った手順です．
（PC環境の問題かもしれませんのでryuzさんの元で再度実装確認頂ければ幸いです）
環境：ZYBO-Z7-20、vivado 2019.1、debian 9、u-boot 4.14.34
（PL）
・zybo_z7_imx219.xprを開く．
・design_1.tclを実行．（既にdesign_1.bdがあるとエラーするので事前に削除）
・Generate Bitstream実行．top.bitをSDにコピー．
（PS）
・@ikwzm氏のFPGA-SoC-Linuxをお借りして実装．
・device-treeを編集、追加ライブラリ（OpenCV等）を実装．
・プログラムをmake、root実行．

宜しくお願い致します．

**Comment by ryuz** [comment]
お世話になります。Ryuzです。

プロジェクトをそのままお使いだとするとDIP-SWは問題ないでしょうか？
実はデバッグ用に
assign cam_gpio = dip_sw[0];
としているのですが
https://www.raspberrypi.org/documentation/hardware/camera/schematics/rpi_SCH_Camera2_2p1.pdf
の回路図の通り電源のENABLEに繋がっておりDIP-SW次第でモジュールが起動せず真っ白(255)になったと記憶しております。

ケアできておらず恐縮なのですが、確認いただけると幸いです。

**Comment by 8622153** [comment]
ryuzさん，お世話になっております．
早速のご確認ありがとうございます．
おっしゃる通りで，SW0の切り替えでカメラ画像を確認できました．
top.v内にそのような記述があったとは，，，完全に見落としてました... :<

お手数おかけしました．ご返答有難うございました．

**Comment by ryuz** [comment]
無事に動作して何よりでした。
デバッグ中に手抜きでDIP-SWにつないでそのままにしていました。申し訳なかったです。
特にDISABLEにする必要性には今のところ出会ってないのでどこかのタイミングで変更しておきます。

稚拙なコードですが、試していただき有難いです。
また何かあればお気軽にお問い合わせください。
